### ISSUE TITLE
gem install broke

### ISSUE THREAD

**Issue by galal-hussein** [mime-types/ruby-mime-types#116]
I am aware that version 3.0 requires Ruby 2.0, I already have locally an old version of mime-types and ruby 1.9.3, still when installing any gem that has mime-types as a dependency, I get the following error:
```
# gem install  aws-s3 -v 0.6.1
ERROR:  Error installing aws-s3:
	mime-types-data requires Ruby version >= 2.0
```

**Comment by halostatue** [comment]
This is a bug with `aws-s3`, because they specify `mime-types >= 0` [as a dependency](https://rubygems.org/gems/aws-s3). I can’t do anything about this except recommend using the `--ignore-dependencies` parameter for `gem install`.

**Comment by galal-hussein** [comment]
That's the point, the gem should be installed correctly since the current version on my system of mime-types is less than 3:
```
# gem list mime-types
mime-types (1.25.1)
```

This problem happened with other gems as well, like paperclip

**Comment by halostatue** [comment]
This is not a bug in `mime-types`, and there’s nothing I can do to fix this in any way.

1. `aws-s3` specifies `mime-types >= 0` (which is, in and of itself, fine because it is probably using the *one* API that I am guaranteed not to change in any version moving forward).
2. Rubygems is resolving `mime-types >= 0` and seeing that there is a later version than the one on your system, so it is trying to install the latest version, which is not compatible with your long-EOLed version of Ruby.

You have three options to resolve this:

1. `gem install aws-s3 --ignore-dependencies`
2. `gem install aws-s3 --minimal-deps`
3. Make a `Gemfile` that specifies `gem 'mime-types', '~> 1.25'` (or `gem 'mime-types', '< 3'`) and use Bundler to install `aws-s3`.

If you can’t use a `Gemfile` (your best choice because it gives you something repeatable), then your best choice is to use `--minimal-deps` (something I didn’t know about until I looked at `gem help install` just now).

**Comment by galal-hussein** [comment]
Thanks for clarification.
