### ISSUE TITLE
mime-types-data v3.2016.0521 regression

### ISSUE THREAD

**Issue by maclover7** [mime-types/ruby-mime-types#121]
Hi!

Since updating to v3.2016.0521 of mime-types-data (note: this is not a manual upgrade, Bundler did this automatically, and when https://github.com/rails/rails/pull/25103/commits/d92ea22ed1b7ba782301718c67ace329182dbfca was committed, this is leading to [this test](https://github.com/rails/rails/blob/master/actionpack/test/dispatch/mime_type_test.rb#L50-55) failing [here](https://travis-ci.org/rails/rails/jobs/132085730#L555) on Travis. Any ideas? 😬

**Comment by halostatue** [comment]
So, this is something that `mime-types-data` isn’t related to. `Mime::Type` (the type in the failing Rails test) is something internal to Rails that isn’t the same as `MIME::Type` (the type of data that `mime-types` and `mime-types-data` deal with. There’s some similarities, but `Mime::Type` has features that `MIME::Type` does not and vice-versa and the purpose is slightly different (I want to be able to take MIME::Type into the parsing direction that `Mime::Type` deals with).

However, this is *purely* a sorting issue:

```diff
--- /Users/austin/old	2016-05-22 16:53:39.000000000 -0400
+++ /Users/austin/new	2016-05-22 16:53:39.000000000 -0400
@@ -52,13 +52,6 @@
   },
   {
     class: "Mime::Type:0xXXXXXX",
-    @synonyms: ["text/x-json", "application/jsonrequest"],
-    @symbol: :json,
-    @string: "application/json",
-    @hash: 1658625877319167784
-  },
-  {
-    class: "Mime::Type:0xXXXXXX",
     @synonyms: [],
     @symbol: :pdf,
     @string: "application/pdf",
@@ -77,5 +70,12 @@
     @symbol: :gzip,
     @string: "application/gzip",
     @hash: 2378352920639632078
+  },
+  {
+    class: "Mime::Type:0xXXXXXX",
+    @synonyms: ["text/x-json", "application/jsonrequest"],
+    @symbol: :json,
+    @string: "application/json",
+    @hash: 1658625877319167784
   }
 ]
```

(The diff here is semi-jsonification so that I could see the difference in a side-by-side diff.)

Put `Mime[:json]` at the end of the `expect` assignment, or change the parsing code so that `json` shows up earlier, and the test will be fixed.

**Comment by maclover7** [comment]
Ahh, gotcha. I saw that `mime-types-data` had been updated in the lockfile, and that this error appeared, so I thought that they could be related. Sorry for the bother 😬
