### ISSUE TITLE
JSON is not binary

### ISSUE THREAD

**Issue by mcandre** [mime-types/ruby-mime-types#68]
JSON should not be `binary?`. It is written and stored as plain text, usually ASCII or UTF-8.

*BSON* is binary.

**Comment by halostatue** [comment]
After further consideration, `#ascii?` and `#binary?` will be remaining as-is because the domain usage is accurate. The data contained in this library doesn’t really indicate whether the information is textual, structured textual, or some sort of binary encoding. One thing that was pointed out to me is that the JSON spec does not specify UTF-8 or ASCII as its encoding, but any valid Unicode—so it could be UTF-32, as well.
