### ISSUE TITLE
mime-types should not forcibly require json

### ISSUE THREAD

**Issue by postmodern** [mime-types/ruby-mime-types#85]
`mime/type.rb` requires 'json' but the mime-types gem does not dependent on any json gem. `mime/types.rb` seems to only require json for the `to_json` method. This could be moved into a separate file, or maybe only define `#to_json` if `defined?(JSON)`. `mime/types/loader.rb` uses JSON to load `data/mime-types.json`, but perhaps this could be converted to YAML to avoid the json dependency?

**Comment by halostatue** [comment]
The default registry store for mime-types 3.0 is the columnar store, required with `require 'mime/types'` or with `require 'mime/types/columnar'`. The JSON store will be used if you `require 'mime/types/full'` or do an explicit `MIME::Types::Loader.new.load(columnar: false)`.

I’m not pursuing the idea of a generated array because of previously noted memory usage issues.
