### ISSUE TITLE
application/vnd.ms-office type support

### ISSUE THREAD

**Issue by Mehonoshin** [mime-types/ruby-mime-types#98]
Hello, guys!

I've recently found out, that unix 'file' command detects some xls, doc files mime type as 'application/vnd.ms-office'.

It looks like this is some generic mime type for office docs.

I'm going to make PR with it to this repo.
What do you think about it?

**Comment by halostatue** [comment]
You can add this, but it will need to be marked as unregistered. It sounds like the `file` command is doing the wrong thing because there are no registered `application/vnd.ms-office` types at IANA. I suspect that it’s doing *just enough* magic to determine that the file in question is an Office-family file, but not doing any more magic to determine the *actual* file type.

**Comment by mikecmpbll** [comment]
I'm having the same issue for .pub (Microsoft Publisher) files. I can't seem to find out what the correct Media Type for publisher files is either. The file command is giving 'application/vnd.ms-office' and the clients' web browsers are giving 'application/vnd.ms-publisher'.

Anyone any clue?

**Comment by halostatue** [comment]
The version of the `file` command I am using reports:

```
something.doc:            application/msword; charset=binary
something.docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document; charset=binary
```

Both of these are legitimate registered types. You may have an old file magic configuration that reports bad data.
